import type { Service } from "../types";

export const servicesAr: Service[] = [
  {
    id: "network-infrastructure",
    slug: "network-infrastructure",
    icon: "network",
    name: "البنية التحتية للشبكات",
    shortDescription: "تصميم ونشر وتحسين شبكات موثوقة للمؤسسات الصغيرة والمدارس والمنظمات.",
    description: "تصمم SYNET وتنشر بنية تحتية شبكية مخصصة لعملياتكم: كابلات منظمة، Wi-Fi مؤسسي، توجيه، تجزئة VLAN ومراقبة. يضمن مهندسونا المعتمدون اتصالاً مستقراً وآمناً وقابلاً للتوسع.",
    benefits: [
      { title: "شبكة موثوقة", description: "بنية احتياطية مُقاسة لاستخدامكم الفعلي مع حد أدنى من التوقف." },
      { title: "أداء محسّن", description: "نقل وlatency وتغطية Wi-Fi مضبوطة للمكاتب والمواقع المتعددة." },
      { title: "أمن مدمج", description: "تجزئة وجدار حماية وحدودي وأفضل الممارسات منذ البداية." },
      { title: "دعم مستمر", description: "صيانة استباقية ومراقبة وتدخل سريع في الموقع." },
    ],
    process: [
      { step: 1, title: "التدقيق والتحليل", description: "تقييم الأنظمة الحالية واحتياجات العمل وقيود الموقع." },
      { step: 2, title: "التصميم", description: "هندسة الشبكة ومخططات وقائمة معدات وخطة نشر معتمدة." },
      { step: 3, title: "النشر", description: "تركيب وتكوين واختبارات حمل في ظروف حقيقية." },
      { step: 4, title: "الإطلاق", description: "انتقال مُراقب وتسليم وثائق وتدريب الفريق." },
      { step: 5, title: "الدعم والنمو", description: "صيانة وتحديثات وتطور مع نمو مؤسستكم." },
    ],
    technologies: ["Cisco", "Fortinet", "Ubiquiti", "HPE Aruba", "MikroTik", "Wireshark", "Zabbix", "PRTG"],
    imageVariant: "network",
  },
  {
    id: "cybersecurity",
    slug: "cybersecurity",
    icon: "shield",
    name: "الأمن السيبراني",
    shortDescription: "حماية استباقية لأنظمتكم وبياناتكم ومستخدميكم من التهديدات الرقمية.",
    description: "ينشر خبراء الأمن لدينا حماية متوافقة مع مستوى المخاطر: جدران حماية متقدمة، كشف التسلل، تقوية النقاط الطرفية ونسخ احتياطي آمن.",
    benefits: [
      { title: "تقليل المخاطر", description: "تحديد الثغرات ومعالجتها قبل استغلالها." },
      { title: "الامتثال", description: "مواءمة مع متطلبات القطاع وأفضل الممارسات الدولية." },
      { title: "استجابة سريعة", description: "إجراءات الحوادث وفريق تفاعلي للحد من الأثر." },
      { title: "رؤية شاملة", description: "مراقبة الأحداث وتقارير واضحة للإدارة." },
    ],
    process: [
      { step: 1, title: "تقييم المخاطر", description: "رسم الأصول والتهديدات وفجوات الأمن." },
      { step: 2, title: "خطة الحماية", description: "إجراءات قصيرة ومتوسطة وطويلة المدى." },
      { step: 3, title: "النشر", description: "تطبيق الحلول وتقوية الأنظمة." },
      { step: 4, title: "الاختبار", description: "اختبار اختراق ومحاكاة وتعديلات." },
      { step: 5, title: "المراقبة", description: "إشراف مستمر ومراجعات دورية." },
    ],
    technologies: ["Fortinet", "Cisco ASA", "CrowdStrike", "Kaspersky", "pfSense", "SIEM", "EDR", "Acronis"],
    imageVariant: "security",
  },
  {
    id: "voip",
    slug: "voip-ip-telephony",
    icon: "phone",
    name: "VoIP والاتصالات عبر IP",
    shortDescription: "حلول اتصالات موحدة لربط فرقكم وعملائكم بكفاءة.",
    description: "تدمج SYNET حلول VoIP احترافية: IP-PBX، هاتف سحابي، مؤتمرات فيديو ورسائل موحدة. خفضوا تكاليف الاتصالات مع جودة صوت أعلى.",
    benefits: [
      { title: "تكاليف مضبوطة", description: "تقليل نفقات الاتصالات عبر VoIP." },
      { title: "التنقل", description: "مكالمات ورسائل وفيديو من أي مكان." },
      { title: "تكامل الأعمال", description: "CRM واستقبال افتراضي وطوابير مكالمات." },
      { title: "جودة الصوت", description: "QoS وتكوين محسّن لصوت واضح." },
    ],
    process: [
      { step: 1, title: "تحليل الاحتياجات", description: "المستخدمون والمواقع وتدفقات المكالمات." },
      { step: 2, title: "هندسة VoIP", description: "اختيار محلي أو سحابي وتخطيط الأرقام." },
      { step: 3, title: "التركيب", description: "نشر IP-PBX وهواتف IP وتكوين المستخدمين." },
      { step: 4, title: "الترحيل", description: "نقل الأرقام وانتقال تدريجي." },
      { step: 5, title: "التدريب والدعم", description: "تأهيل المستخدمين ومساعدة تقنية مستمرة." },
    ],
    technologies: ["3CX", "Cisco CUCM", "Yealink", "Grandstream", "SIP Trunk", "Microsoft Teams", "Asterisk", "QoS"],
    imageVariant: "voip",
  },
  {
    id: "web-development",
    slug: "web-development",
    icon: "code",
    name: "تطوير الويب",
    shortDescription: "مواقع وتطبيقات ويب احترافية عالية الأداء متوافقة مع علامتكم.",
    description: "من المواقع المؤسسية إلى التطبيقات التجارية، تبني SYNET حلول ويب حديثة ومتجاوبة وآمنة مع SEO ودعم متعدد اللغات.",
    benefits: [
      { title: "صورة احترافية", description: "تصميم نظيف وموثوق يناسب المؤسسات." },
      { title: "الأداء", description: "مواقع سريعة ومحسّنة للجوال." },
      { title: "أمن الويب", description: "HTTPS وحماية النماذج وتحديثات منتظمة." },
      { title: "قابلية التوسع", description: "بنية مرنة تنمو مع نشاطكم." },
    ],
    process: [
      { step: 1, title: "التحديد", description: "الأهداف وهيكل الموقع والمواصفات." },
      { step: 2, title: "التصميم", description: "نماذج معتمدة وفق هويتكم." },
      { step: 3, title: "التطوير", description: "تكامل وتطبيق واختبارات جودة." },
      { step: 4, title: "الإطلاق", description: "استضافة وDNS وSSL وقبول نهائي." },
      { step: 5, title: "الصيانة", description: "تحديثات ونسخ احتياطي وتطويرات." },
    ],
    technologies: ["Next.js", "React", "WordPress", "TypeScript", "Tailwind CSS", "Vercel", "PostgreSQL", "SEO"],
    imageVariant: "web",
  },
  {
    id: "cloud-solutions",
    slug: "cloud-solutions",
    icon: "cloud",
    name: "حلول السحابة",
    shortDescription: "ترحيل واستضافة وإدارة آمنة لأعباء العمل السحابية.",
    description: "ترافقكم SYNET في التحول السحابي: تقييم وترحيل وبنية هجينة وإدارة يومية على المنصات الرائدة.",
    benefits: [
      { title: "المرونة", description: "موارد حسب الطلب دون استثمار ثقيل." },
      { title: "توفر عالٍ", description: "بنى مرنة مع نسخ احتياطي وتعافٍ." },
      { title: "تحسين التكاليف", description: "تحجيم وحوكمة للتحكم في الفواتير." },
      { title: "أمن السحابة", description: "هوية وتشفير وامتثال مدمج." },
    ],
    process: [
      { step: 1, title: "تقييم السحابة", description: "جرد التطبيقات واستراتيجية الترحيل." },
      { step: 2, title: "الهندسة", description: "شبكة وهوية وتخزين وخطة انتقال." },
      { step: 3, title: "الترحيل", description: "نقل تدريجي مع اختبارات." },
      { step: 4, title: "التحسين", description: "FinOps ومراقبة وضبط الموارد." },
      { step: 5, title: "خدمات مُدارة", description: "إشراف وتصحيحات ودعم." },
    ],
    technologies: ["Microsoft Azure", "AWS", "Google Cloud", "VMware", "Docker", "Kubernetes", "Veeam", "Terraform"],
    imageVariant: "cloud",
  },
  {
    id: "it-support",
    slug: "it-support-maintenance",
    icon: "headset",
    name: "الدعم والصيانة التقنية",
    shortDescription: "مساعدة تقنية سريعة وصيانة استباقية لضمان استمرارية أعمالكم.",
    description: "يحافظ فريق الدعم على عمل بنيتكم التقنية: مكتب مساعدة وصيانة وقائية وإدارة الحوادث وتجديد المعدات.",
    benefits: [
      { title: "سرعة الاستجابة", description: "تذاكر وفق SLA مع تصعيد للمهندسين." },
      { title: "استمرارية الأعمال", description: "صيانة وقائية لتقليل الأعطال." },
      { title: "جهة اتصال واحدة", description: "فريق واحد للبنية والمحطات والبرمجيات." },
      { title: "تقارير واضحة", description: "لوحات معلومات وتقارير شهرية." },
    ],
    process: [
      { step: 1, title: "الإعداد", description: "جرد المعدات وتوثيق وSLA." },
      { step: 2, title: "مكتب المساعدة", description: "دعم المستخدمين عبر تذكرة أو هاتف." },
      { step: 3, title: "صيانة وقائية", description: "زيارات وتحديثات وفحوصات." },
      { step: 4, title: "إدارة الحوادث", description: "تشخيص وحل وتحليل السبب الجذري." },
      { step: 5, title: "تحسين مستمر", description: "مراجعات ربع سنوية وتوصيات." },
    ],
    technologies: ["GLPI", "TeamViewer", "Microsoft 365", "Intune", "Active Directory", "WSUS", "Veeam", "N-able"],
    imageVariant: "support",
  },
  {
    id: "cctv",
    slug: "cctv-access-control",
    icon: "camera",
    name: "المراقبة والتحكم في الوصول",
    shortDescription: "أمن مادي ذكي لحماية مقراتكم ومعداتكم وموظفيكم.",
    description: "تنشر SYNET أنظمة مراقبة IP وتحكم في الوصول: كاميرات HD وتسجيل مركزي وعرض عن بُعد وإدارة البطاقات.",
    benefits: [
      { title: "حماية 24/7", description: "مراقبة مستمرة مع تنبيهات وتسجيل آمن." },
      { title: "تحكم في الدخول", description: "صلاحيات دقيقة حسب المنطقة والوقت." },
      { title: "أدلة موثوقة", description: "تسجيلات مؤرخة للتحقيقات." },
      { title: "تكامل", description: "فيديو وتحكم وإنذار على منصة واحدة." },
    ],
    process: [
      { step: 1, title: "دراسة الموقع", description: "نقاط الدخول والمناطق الميتاء والمتطلبات." },
      { step: 2, title: "التحجيم", description: "اختيار الكاميرات والمسجلات والكابلات." },
      { step: 3, title: "التركيب", description: "تركيب وتكوين واختبارات التغطية." },
      { step: 4, title: "الإعداد", description: "ملفات الوصول والاحتفاظ والوصول الآمن." },
      { step: 5, title: "الصيانة", description: "فحوصات وتحديثات ودعم." },
    ],
    technologies: ["Hikvision", "Dahua", "Axis", "Milestone", "Bosch", "ZKTeco", "HID", "PoE"],
    imageVariant: "cctv",
  },
];
