import type { SitePagesCopy } from "../types";

export const siteEn: SitePagesCopy = {
  notFound: {
    title: "Page not found",
    description: "The page you requested does not exist or has been moved.",
    home: "Back to homepage",
  },
  contact: {
    metaTitle: "Contact SYNET | IT Solutions & Training",
    metaDescription: "Contact SYNET for IT projects or training enrollment. Response within one business day.",
    heading: "Contact SYNET",
    lead: "Questions about our solutions or training programs? Our team responds within one business day.",
    formHeading: "Send a message",
    responseTime: "Response time: 1 business day",
    successTitle: "Message sent",
    successMessage: "Thank you. A SYNET advisor will contact you shortly.",
    submit: "Send message",
    submitting: "Sending…",
    fields: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      organization: "Organization (optional)",
      intent: "Your inquiry concerns",
      intentOptions: [
        { value: "business", label: "Business solutions" },
        { value: "training", label: "Training center" },
        { value: "both", label: "Both" },
        { value: "other", label: "Other" },
      ],
      subject: "Subject (optional)",
      message: "Message",
      consent: "I agree that SYNET may process my data to respond to my request, in accordance with the",
      consentLink: "privacy policy",
    },
    errors: { required: "This field is required", email: "Invalid email address", consent: "You must accept the privacy policy" },
    nextSteps: [
      "Our team reviews your request",
      "An advisor contacts you by email or phone",
      "We propose the next step (quote, enrollment, meeting)",
    ],
  },
  about: {
    metaTitle: "About SYNET | IT Solutions & Training",
    metaDescription: "Learn about SYNET: enterprise IT solutions and professional training in Morocco.",
    heading: "About SYNET",
    lead: "SYNET helps organizations build reliable IT systems and professionals develop practical technology skills.",
    missionHeading: "Our mission",
    mission: "Help businesses build secure, reliable infrastructure while enabling individuals to gain job-ready, practical skills.",
    values: [
      { title: "Technical excellence", description: "Certified engineers and trainers active in the field." },
      { title: "Pragmatism", description: "Solutions and training focused on outcomes, not theory alone." },
      { title: "Proximity", description: "A single point of contact for IT projects and team development." },
    ],
    ctaQuote: "Request a quote",
    ctaTraining: "View training programs",
  },
  partners: {
    metaTitle: "Partners & certifications | SYNET",
    heading: "Technologies & certifications",
    lead: "Our teams master leading market technologies and prepare candidates for recognized certifications.",
    technologies: "Cisco · Microsoft · Linux · SAP · Fortinet · Cloud (AWS/Azure)",
    note: "Official partnerships and certifications are available on request and updated regularly.",
  },
  careers: {
    metaTitle: "Careers | SYNET",
    heading: "Join SYNET",
    lead: "We hire engineers, consultants, and trainers passionate about technology and knowledge transfer.",
    cta: "Contact us",
  },
  sectors: {
    metaTitle: "Industries | SYNET",
    metaDescription: "IT solutions for SMEs, schools, clinics, factories, and organizations in Morocco.",
    heading: "Solutions for your industry",
    lead: "Every organization has specific constraints. SYNET adapts services and training to your context.",
    viewServices: "View our services",
    requestQuote: "Request a quote",
    items: {
      pme: { name: "SMEs", description: "Outsource IT with a responsive partner: support, security, and infrastructure at controlled cost.", challenges: ["Limited IT budget", "Need for responsiveness", "Data protection"] },
      ecoles: { name: "Schools", description: "High-performance networks, cybersecurity, and computer labs for reliable learning.", challenges: ["Campus connectivity", "Student data protection", "Preventive maintenance"] },
      cliniques: { name: "Clinics", description: "Reliable, secure infrastructure for medical systems and patient data confidentiality.", challenges: ["Critical availability", "Health data compliance", "Rapid support"] },
      usines: { name: "Factories", description: "Industrial networks, CCTV, and maintenance for connected production sites.", challenges: ["Harsh environments", "Physical and digital security", "Production continuity"] },
      "organisations-gouvernementales": { name: "Government organizations", description: "Solutions aligned with public sector requirements: security, audit, and project support.", challenges: ["Compliance requirements", "Multi-site projects", "Data sovereignty"] },
    },
  },
  caseStudies: {
    metaTitle: "Case studies | SYNET",
    metaDescription: "IT projects and case studies delivered by SYNET for organizations in Morocco.",
    heading: "Our work",
    lead: "See how SYNET supports clients on infrastructure, security, and training.",
    comingSoon: "New case studies will be published soon. Contact us to discuss similar projects.",
    cta: "Request a quote",
  },
  resources: {
    metaTitle: "Resources | SYNET",
    heading: "Resources",
    lead: "Articles, guides, and answers to common questions about our services and training.",
    blogTitle: "Blog",
    blogLead: "Technical advice, news, and field insights.",
    faqTitle: "FAQ",
    faqLead: "Answers to frequently asked questions.",
    comingSoon: "Content coming soon.",
  },
  faq: {
    metaTitle: "FAQ | SYNET",
    heading: "Frequently asked questions",
    lead: "Quick answers about our services, training, and enrollment.",
    items: [
      { question: "How quickly do you respond to quote requests?", answer: "We aim to respond within one business day after receiving your request.", division: "business" },
      { question: "Do you offer IT support for SMEs?", answer: "Yes. Our support and maintenance service covers helpdesk, managed services, and on-site intervention.", division: "business" },
      { question: "Do training programs include hands-on labs?", answer: "Yes. All programs combine theory and practical exercises in our equipped lab.", division: "training" },
      { question: "How do I enroll in a course?", answer: "Complete the online enrollment form or contact us. Our team confirms your seat within one business day.", division: "training" },
    ],
  },
  blog: {
    metaTitle: "Blog | SYNET",
    heading: "SYNET Blog",
    lead: "News, guides, and expertise in IT solutions and professional training.",
    comingSoon: "The blog will be available soon. Contact us to stay informed.",
  },
  legal: {
    mentions: { metaTitle: "Legal notice | SYNET", heading: "Legal notice", updated: "Last updated: June 2026", body: ["Publisher: SYNET — [Legal name and full address to be completed].", "Publication director: [Name to be completed].", "Hosting: [Host to be completed].", "Contact: contact@synet.ma", "Information on this site is indicative and may change without notice."] },
    privacy: { metaTitle: "Privacy policy | SYNET", heading: "Privacy policy", updated: "Last updated: June 2026", body: ["SYNET collects data submitted via forms (name, email, phone, message) only to process contact, quote, or enrollment requests.", "Legal basis: pre-contractual measures and legitimate interest in responding to inquiries.", "Data is retained as long as needed to process your request, then archived per legal obligations.", "You may request access, correction, or deletion at contact@synet.ma.", "Full contact details and DPO information will be provided at final production launch."] },
    terms: { metaTitle: "Terms of use | SYNET", heading: "Terms of use", updated: "Last updated: June 2026", body: ["Use of synet.ma implies acceptance of these terms.", "Content is protected by copyright. Unauthorized reproduction is prohibited.", "SYNET strives for accuracy but does not guarantee error-free information.", "External links are not SYNET's responsibility.", "Applicable law: Moroccan law. Competent court: [to be completed]."] },
  },
  forms: { referenceLabel: "Your request reference", nextStepsTitle: "Next steps" },
};
