export const adminCopy = {
  brand: "SYNET Admin",
  tagline: "Console interne SYNET",
  login: {
    title: "Connexion administrateur",
    email: "Adresse e-mail",
    password: "Mot de passe",
    submit: "Se connecter",
    submitting: "Connexion…",
    forgot: "Mot de passe oublié ?",
    error: "Identifiants incorrects ou compte désactivé.",
    firebaseError: "Service d'authentification indisponible.",
  },
  nav: {
    dashboard: "Tableau de bord",
    operations: "Opérations",
    registrations: "Inscriptions formation",
    quotes: "Demandes de devis",
    messages: "Messages contact",
    content: "Contenu",
    courses: "Formations",
    testimonials: "Témoignages",
    siteContent: "Contenu site",
    globals: "Paramètres globaux",
    administration: "Administration",
    users: "Utilisateurs",
    profile: "Profil",
    logout: "Déconnexion",
  },
  dashboard: {
    title: "Tableau de bord",
    subtitle: "Vue d'ensemble des demandes entrantes",
    registrations: "Inscriptions",
    quotes: "Devis",
    messages: "Messages",
    leads: "Leads",
    new: "nouveau(x)",
    viewAll: "Voir tout",
  },
  table: {
    reference: "Référence",
    status: "Statut",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    course: "Formation",
    company: "Entreprise",
    service: "Service",
    subject: "Objet",
    createdAt: "Date",
    empty: "Aucun enregistrement pour le moment.",
    loading: "Chargement…",
    error: "Impossible de charger les données.",
  },
  status: {
    new: "Nouveau",
    in_review: "En cours",
    contacted: "Contacté",
    qualified: "Qualifié",
    enrolled: "Inscrit",
    converted: "Converti",
    proposal_sent: "Proposition envoyée",
    won: "Gagné",
    lost: "Perdu",
    spam: "Spam",
    archived: "Archivé",
  },
  comingSoon: {
    title: "Module en préparation",
    body: "Cette section sera disponible dans une prochaine version.",
    back: "Retour au tableau de bord",
  },
  profile: {
    title: "Mon profil",
    role: "Rôle",
    email: "E-mail",
  },
} as const;

export function statusLabel(status: string): string {
  return adminCopy.status[status as keyof typeof adminCopy.status] ?? status;
}
